/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.*;
import Modelo.*;
import Modelo.TrabajoGrado.tipo_grado;
import java.awt.Color;
import java.util.InputMismatchException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Michael
 */
public class Insertar extends javax.swing.JDialog {

    /**
     * Creates new form Insertar
     */
    GestorDocumentos gestor;
    String seleccionado;
    Libro mi_libro;
    Revista mi_revista;
    Publicacion mi_public;
    TrabajoGrado mi_trabajo;
    
    public Insertar(java.awt.Frame parent, boolean modal, GestorDocumentos gd) {
        super(parent, modal);
        gestor = gd;
        initComponents();
        seleccionado = "Libro";
        Identificar();
        this.jTextFieldTitulo.setText("Ej: Ingenieria del Software");
        this.jTextFieldUbicacion.setText("Ej: Lenguajes de Programación");
        this.jTextFieldCantidad.setText("Ingrese unicamente números enteros");
        this.jTextFieldAutor.setText("Ej: Ian Sommerville");
    }

    private Insertar(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxDocs = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jPanelDatos = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelAutor = new javax.swing.JLabel();
        jLabelUbicacion = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jLRequerido1 = new javax.swing.JLabel();
        jLRequerido2 = new javax.swing.JLabel();
        jLRequerido3 = new javax.swing.JLabel();
        jTextFieldAutor = new javax.swing.JTextField();
        jTextFieldTitulo = new javax.swing.JTextField();
        jTextFieldUbicacion = new javax.swing.JTextField();
        jTextFieldCantidad = new javax.swing.JTextField();
        jtxtReq1 = new javax.swing.JTextField();
        jtxtReq2 = new javax.swing.JTextField();
        jtxtReq3 = new javax.swing.JTextField();
        Separador1 = new javax.swing.JSeparator();
        jButtonAgregar = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Insertar Documento - FIS UNED");
        setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jComboBoxDocs.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jComboBoxDocs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Libro", "Revista", "Trabajo de Grado", "Publicación" }));
        jComboBoxDocs.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxDocsItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel1.setText("Seleccione un tipo de documento");

        jPanelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanelDatos.setForeground(new java.awt.Color(102, 153, 255));
        jPanelDatos.setToolTipText("Complete cada uno de los espacios solicitados");

        jLabelTitulo.setText("Título:");

        jLabelAutor.setText("Autor: ");

        jLabelUbicacion.setText("Ubicación: ");

        jLabelCantidad.setText("Número de Ejemplares:");

        jLRequerido1.setText("Primer Campo Requerido:");

        jLRequerido2.setText("Segundo Campo Requerido:");

        jLRequerido3.setText("Tercer Campo Requerido:");

        jTextFieldAutor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldAutorFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldAutorFocusGained(evt);
            }
        });

        jTextFieldTitulo.setNextFocusableComponent(jTextFieldAutor);
        jTextFieldTitulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTituloFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldTituloFocusGained(evt);
            }
        });

        jTextFieldUbicacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUbicacionFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUbicacionFocusGained(evt);
            }
        });

        jTextFieldCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCantidadFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldCantidadFocusGained(evt);
            }
        });

        jtxtReq1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtReq1FocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtReq1FocusGained(evt);
            }
        });

        jtxtReq2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtReq2FocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtReq2FocusGained(evt);
            }
        });

        jtxtReq3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtReq3FocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtReq3FocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAutor)
                            .addComponent(jLabelTitulo)
                            .addComponent(jLabelUbicacion)
                            .addComponent(jLabelCantidad)
                            .addComponent(jLRequerido1))
                        .addGap(30, 30, 30)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTitulo)
                            .addComponent(jTextFieldAutor)
                            .addComponent(jTextFieldUbicacion)
                            .addComponent(jTextFieldCantidad)
                            .addComponent(jtxtReq1)))
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLRequerido2)
                            .addComponent(jLRequerido3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtReq2)
                            .addComponent(jtxtReq3))))
                .addContainerGap())
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAutor)
                    .addComponent(jTextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUbicacion)
                    .addComponent(jTextFieldUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCantidad)
                    .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLRequerido1)
                    .addComponent(jtxtReq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLRequerido2)
                    .addComponent(jtxtReq2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLRequerido3)
                    .addComponent(jtxtReq3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jButtonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/document-icon.png"))); // NOI18N
        jButtonAgregar.setText("Agregar a Biblioteca");
        jButtonAgregar.setToolTipText("Agregar el Documento a la Biblioteca");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jButtonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1374972677_back-alt.png"))); // NOI18N
        jButtonAtras.setText("Volver al Menú Principal");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Separador1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxDocs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(jButtonAgregar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxDocs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAtras)
                    .addComponent(jButtonAgregar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:
        try
        {
            if (this.jComboBoxDocs.getSelectedIndex()==0) 
            {
                mi_libro = new Libro(this.jTextFieldTitulo.getText(), this.jTextFieldAutor.getText(),this.jTextFieldUbicacion.getText(), Integer.parseInt(this.jTextFieldCantidad.getText()),this.jtxtReq1.getText(), Integer.parseInt(this.jtxtReq2.getText()));
                gestor.Agregar(mi_libro);
            }
            else if(this.jComboBoxDocs.getSelectedIndex() == 1)
            {
                mi_revista = new Revista(this.jTextFieldTitulo.getText(), this.jTextFieldAutor.getText(),this.jTextFieldUbicacion.getText(), Integer.parseInt(this.jTextFieldCantidad.getText()),this.jtxtReq1.getText(),this.jtxtReq2.getText(), Integer.parseInt(this.jtxtReq3.getText()));
                gestor.Agregar(mi_revista);
            }
            else if(this.jComboBoxDocs.getSelectedIndex() == 2)
            {
                mi_trabajo = new TrabajoGrado(this.jTextFieldTitulo.getText(), this.jTextFieldAutor.getText(),this.jTextFieldUbicacion.getText(), Integer.parseInt(this.jTextFieldCantidad.getText()),tipo_grado.valueOf(this.jtxtReq1.getText()),this.jtxtReq2.getText());
                gestor.Agregar(mi_trabajo);
            }
            else if(this.jComboBoxDocs.getSelectedIndex() == 3)
            {
                mi_public = new Publicacion(this.jTextFieldTitulo.getText(), this.jTextFieldAutor.getText(),this.jTextFieldUbicacion.getText(), Integer.parseInt(this.jTextFieldCantidad.getText()),this.jtxtReq1.getText());
                gestor.Agregar(mi_public);
            }

            else
            {
                // Esto no deberia pasar
            }
            JOptionPane.showMessageDialog(null, "El documento ha sido agregado", "Documento Agregado", JOptionPane.PLAIN_MESSAGE);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Verifique los datos, algunos no son correctos", "Datos no Válidos", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jComboBoxDocsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxDocsItemStateChanged
        
        seleccionado = this.jComboBoxDocs.getSelectedItem().toString();
        this.jPanelDatos.setVisible(true);
        this.jButtonAgregar.setVisible(true);
        Identificar();
    }//GEN-LAST:event_jComboBoxDocsItemStateChanged

    private void jTextFieldUbicacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUbicacionFocusLost
        
        if (this.jTextFieldUbicacion.getText().isEmpty()) 
        {
            this.jTextFieldUbicacion.setForeground(Color.red);
            this.jTextFieldUbicacion.setText("Ej: Lenguajes de Programación");
        }
    }//GEN-LAST:event_jTextFieldUbicacionFocusLost

    private void jTextFieldUbicacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUbicacionFocusGained
        
        if (this.jTextFieldUbicacion.getText().equals("Ej: Lenguajes de Programación")) 
        {
            this.jTextFieldUbicacion.setForeground(Color.BLACK);
            this.jTextFieldUbicacion.setText(null);
        }
    }//GEN-LAST:event_jTextFieldUbicacionFocusGained

    private void jTextFieldCantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCantidadFocusLost
        if (this.jTextFieldCantidad.getText().isEmpty()) 
        {
            this.jTextFieldCantidad.setForeground(Color.red);
            this.jTextFieldCantidad.setText("Ingrese unicamente números enteros");
        }
    }//GEN-LAST:event_jTextFieldCantidadFocusLost

    private void jTextFieldCantidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCantidadFocusGained
        // TODO add your handling code here:
        if (this.jTextFieldCantidad.getText().equals("Ingrese unicamente números enteros")) 
        {
            this.jTextFieldCantidad.setForeground(Color.BLACK);
            this.jTextFieldCantidad.setText(null);
        }
    }//GEN-LAST:event_jTextFieldCantidadFocusGained

    private void jTextFieldTituloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTituloFocusLost
        
        if (this.jTextFieldTitulo.getText().isEmpty()) 
        {
            this.jTextFieldTitulo.setForeground(Color.red);
            this.jTextFieldTitulo.setText("Ej: Ingenieria del Software");
        }
    }//GEN-LAST:event_jTextFieldTituloFocusLost

    private void jTextFieldTituloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTituloFocusGained
        
        if (this.jTextFieldTitulo.getText().equals("Ej: Ingenieria del Software")) 
        {
            this.jTextFieldTitulo.setForeground(Color.BLACK);
            this.jTextFieldTitulo.setText(null);
        }
    }//GEN-LAST:event_jTextFieldTituloFocusGained

    private void jTextFieldAutorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAutorFocusGained
        
        if (this.jTextFieldAutor.getText().equals("Ej: Ian Sommerville")) 
        {
            this.jTextFieldAutor.setForeground(Color.BLACK);
            this.jTextFieldAutor.setText(null);
        }
    }//GEN-LAST:event_jTextFieldAutorFocusGained

    private void jTextFieldAutorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAutorFocusLost
        
        if (this.jTextFieldAutor.getText().isEmpty()) 
        {
            this.jTextFieldAutor.setForeground(Color.red);
            this.jTextFieldAutor.setText("Ej: Ian Sommerville");
        }
    }//GEN-LAST:event_jTextFieldAutorFocusLost

    private void jtxtReq1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtReq1FocusLost
        
        switch(this.seleccionado)
        {
            case "Libro": // Espacios necesarios para un libro
                    if (this.jtxtReq1.getText().isEmpty()) 
                    {
                        this.jtxtReq1.setForeground(Color.red);
                        this.jtxtReq1.setText("Ej: PEARSON");
                    }
                    if (this.jtxtReq2.getText().isEmpty()) 
                    {
                        this.jtxtReq2.setForeground(Color.red);
                        this.jtxtReq2.setText("Ej: 2008");
                    }
                    
                break;
            case "Revista": // Espacios Necesarios para una Revista
                    if (this.jtxtReq1.getText().isEmpty()) 
                    {
                        this.jtxtReq1.setForeground(Color.red);
                        this.jtxtReq1.setText("Ej: ARQ");
                    }
                    if (this.jtxtReq2.getText().isEmpty()) 
                    {
                        this.jtxtReq2.setForeground(Color.red);
                        this.jtxtReq2.setText("Ej: Enero");
                    }
                    if (this.jtxtReq3.getText().isEmpty()) 
                    {
                        this.jtxtReq3.setForeground(Color.red);
                        this.jtxtReq3.setText("Ej: 2013");
                    }
                break;
            case "Trabajo de Grado":
                    if (this.jtxtReq1.getText().isEmpty()) 
                    {
                        this.jtxtReq1.setForeground(Color.red);
                        this.jtxtReq1.setText("D(Diplomado), B(Bachillerato), L(Licenciatura)");
                    }
                    if (this.jtxtReq2.getText().isEmpty()) 
                    {
                        this.jtxtReq2.setForeground(Color.red);
                        this.jtxtReq2.setText("Ej: UNED");
                    }
                break;
            case "Publicación":
                    if (this.jtxtReq1.getText().isEmpty()) 
                    {
                        this.jtxtReq1.setForeground(Color.red);
                        this.jtxtReq1.setText("Ej: La Nación");
                    }
                break;
            default:
                //Esto no debería pasar
        }   
    }//GEN-LAST:event_jtxtReq1FocusLost

    private void jtxtReq2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtReq2FocusLost

        switch(this.seleccionado)
        {
            case "Libro": // Espacios necesarios para un libro
                    if (this.jtxtReq2.getText().isEmpty()) 
                    {
                        this.jtxtReq2.setForeground(Color.red);
                        this.jtxtReq2.setText("Ej: 2008");
                    }
                    
                break;
            case "Revista": // Espacios Necesarios para una Revista
                    if (this.jtxtReq2.getText().isEmpty()) 
                    {
                        this.jtxtReq2.setForeground(Color.red);
                        this.jtxtReq2.setText("Ej: Enero");
                    }
                break;
            case "Trabajo de Grado":
                    if (this.jtxtReq2.getText().isEmpty()) 
                    {
                        this.jtxtReq2.setForeground(Color.red);
                        this.jtxtReq2.setText("Ej: UNED");
                    }
                break;
            default:
                //Esto no debería pasar
        } 
    }//GEN-LAST:event_jtxtReq2FocusLost

    private void jtxtReq3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtReq3FocusLost

        if (this.jtxtReq3.getText().isEmpty()) 
        {
            this.jtxtReq3.setForeground(Color.red);
            this.jtxtReq3.setText("Ej: 2013");
        }
    }//GEN-LAST:event_jtxtReq3FocusLost

    private void jtxtReq1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtReq1FocusGained

        switch(this.seleccionado)
        {
            case "Libro": // Espacios necesarios para un libro
                    if (this.jtxtReq1.getText().equals("Ej: PEARSON")) 
                    {
                        this.jtxtReq1.setForeground(Color.BLACK);
                        this.jtxtReq1.setText(null);
                    }
                break;
            case "Revista": // Espacios Necesarios para una Revista
                    if (this.jtxtReq1.getText().equals("Ej: ARQ")) 
                    {
                        this.jtxtReq1.setForeground(Color.BLACK);
                        this.jtxtReq1.setText(null);
                    }
                break;
            case "Trabajo de Grado":
                    if (this.jtxtReq1.getText().equals("D(Diplomado), B(Bachillerato), L(Licenciatura)")) 
                    {
                        this.jtxtReq1.setForeground(Color.BLACK);
                        this.jtxtReq1.setText(null);
                    }
                break;
            case "Publicación":
                    if (this.jtxtReq1.getText().equals("Ej: La Nación")) 
                    {
                        this.jtxtReq1.setForeground(Color.BLACK);
                        this.jtxtReq1.setText(null);
                    }
                break;
            default:
                //Esto no debería pasar
        }
    }//GEN-LAST:event_jtxtReq1FocusGained

    private void jtxtReq2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtReq2FocusGained

        switch(this.seleccionado)
        {
            case "Libro": // Espacios necesarios para un libro
                    if (this.jtxtReq2.getText().equals("Ej: 2008")) 
                    {
                        this.jtxtReq2.setForeground(Color.BLACK);
                        this.jtxtReq2.setText(null);
                    }
                    
                break;
            case "Revista": // Espacios Necesarios para una Revista
                    if (this.jtxtReq2.getText().equals("Ej: Enero")) 
                    {
                        this.jtxtReq2.setForeground(Color.BLACK);
                        this.jtxtReq2.setText(null);
                    }
                break;
            case "Trabajo de Grado":
                    if (this.jtxtReq2.getText().equals("Ej: UNED")) 
                    {
                        this.jtxtReq2.setForeground(Color.BLACK);
                        this.jtxtReq2.setText(null);
                    }
                break;
            default:
                //Esto no debería pasar
        } 
    }//GEN-LAST:event_jtxtReq2FocusGained

    private void jtxtReq3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtReq3FocusGained
        
        if (this.jtxtReq3.getText().equals("Ej: 2013")) 
        {
            this.jtxtReq3.setForeground(Color.BLACK);
            this.jtxtReq3.setText(null);
        }
    }//GEN-LAST:event_jtxtReq3FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Insertar dialog = new Insertar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Separador1;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JComboBox jComboBoxDocs;
    private javax.swing.JLabel jLRequerido1;
    private javax.swing.JLabel jLRequerido2;
    private javax.swing.JLabel jLRequerido3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUbicacion;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldTitulo;
    private javax.swing.JTextField jTextFieldUbicacion;
    private javax.swing.JTextField jtxtReq1;
    private javax.swing.JTextField jtxtReq2;
    private javax.swing.JTextField jtxtReq3;
    // End of variables declaration//GEN-END:variables

    private void Identificar() 
    {
        switch(this.seleccionado)
        {
            case "Libro": // Espacios necesarios para un libro
                    this.jLRequerido1.setText("Editorial:");
                    this.jLRequerido2.setText("Año de Publicación:");
                    this.jLRequerido2.setVisible(true);
                    this.jtxtReq2.setVisible(true);
                    this.jLRequerido3.setVisible(false);
                    this.jtxtReq3.setVisible(false);
                    
                    this.jtxtReq1.setText("Ej: PEARSON");
                    this.jtxtReq2.setText("Ej: 2008");
                break;
            case "Revista": // Espacios Necesarios para una Revista
                    this.jLRequerido1.setText("Casa de Edición:");
                    this.jLRequerido2.setText("Mes de Publicación:");
                    this.jLRequerido3.setText("Año de Publicación:");
                    this.jLRequerido2.setVisible(true);
                    this.jtxtReq2.setVisible(true);
                    this.jLRequerido3.setVisible(true);
                    this.jtxtReq3.setVisible(true);
                    this.jtxtReq1.setText("Ej: ARQ");
                    this.jtxtReq2.setText("Ej: Enero");
                    this.jtxtReq3.setText("Ej: 2013");
                break;
            case "Trabajo de Grado":
                    this.jLRequerido1.setText("Tipo de Grado:");
                    this.jLRequerido2.setText("Universidad:");
                    this.jLRequerido3.setVisible(false);
                    this.jtxtReq3.setVisible(false);
                    this.jLRequerido2.setVisible(true);
                    this.jtxtReq2.setVisible(true);
                    this.jtxtReq1.setText("D(Diplomado), B(Bachillerato), L(Licenciatura)");
                    this.jtxtReq2.setText("Ej: UNED");
                break;
            case "Publicación":
                    this.jLRequerido1.setText("Referencia al Periódico:");
                    this.jLRequerido2.setVisible(false);
                    this.jLRequerido3.setVisible(false);
                    this.jtxtReq2.setVisible(false);
                    this.jtxtReq3.setVisible(false);
                    this.jtxtReq1.setText("Ej: La Nación");
                    
                break;
            default:
                //Esto no debería pasar
        }
                        
        }
}
